-- Добавление UTM-меток, Яндекс.Метрика ID и страницы-источника в таблицы курсов

ALTER TABLE course_enrollments
  ADD COLUMN utm_source VARCHAR(255) DEFAULT NULL,
  ADD COLUMN utm_medium VARCHAR(255) DEFAULT NULL,
  ADD COLUMN utm_campaign VARCHAR(255) DEFAULT NULL,
  ADD COLUMN utm_content VARCHAR(255) DEFAULT NULL,
  ADD COLUMN utm_term VARCHAR(255) DEFAULT NULL,
  ADD COLUMN ym_uid VARCHAR(50) DEFAULT NULL,
  ADD COLUMN source_page VARCHAR(500) DEFAULT NULL;

ALTER TABLE course_consultations
  ADD COLUMN utm_source VARCHAR(255) DEFAULT NULL,
  ADD COLUMN utm_medium VARCHAR(255) DEFAULT NULL,
  ADD COLUMN utm_campaign VARCHAR(255) DEFAULT NULL,
  ADD COLUMN utm_content VARCHAR(255) DEFAULT NULL,
  ADD COLUMN utm_term VARCHAR(255) DEFAULT NULL,
  ADD COLUMN ym_uid VARCHAR(50) DEFAULT NULL,
  ADD COLUMN source_page VARCHAR(500) DEFAULT NULL;
