-- 169_olympiad_slug_redirects.sql
-- Редиректы удалённых детальных страниц олимпиад на каталог предмета/роли.
--
-- Причина: database/migrate_olympiads_to_grades.php при дроблении олимпиад по классам
-- сделал UPDATE olympiads SET slug=… WHERE id=… и НЕ сохранил старые slug. 127 старых
-- детальных URL (Я.Метрика, июнь–сентябрь 2026, 1390 визитов) отдают HTTP 404.
-- Механизм redirect_to_slug (миграция 157) есть только у publications/competitions.
--
-- Решение: таблица old_slug → target_url; pages/olympiad-detail.php при ненайденном
-- slug отдаёт 301 на каталог соответствующего предмета/роли. Цель — каталог
-- (не конкретная новая олимпиада): старый диапазон раздроблён на десятки тем-по-классам.
-- Аудитория цели: pedagogi, кроме случаев со shkolnikam в контексте.
--
-- Карта согласована с владельцем продукта 2026-09-07 (см. database/olympiad_slug_redirects_REVIEW.tsv).
-- migrate.php игнорирует "already exists"/"Duplicate" — повторный прогон безопасен.
-- INSERT IGNORE — не перезатирает уже поправленные вручную строки на проде.

CREATE TABLE IF NOT EXISTS olympiad_slug_redirects (
    old_slug   VARCHAR(255) NOT NULL PRIMARY KEY,
    target_url VARCHAR(255) NOT NULL,
    note       VARCHAR(64)  NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO olympiad_slug_redirects (old_slug, target_url, note) VALUES
  ('olimpiada-bibliotechnoe-delo-v-obrazovanii', '/olimpiady/pedagogi/bibliotekar/', 'auto'),
  ('olimpiada-okruzhayushchiy-mir-1-4-klass', '/olimpiady/pedagogi/okruzhayushchiy-mir/', 'diapason'),
  ('olimpiada-russkiy-yazyk-5-8-klass', '/olimpiady/pedagogi/russkiy-yazyk/', 'diapason'),
  ('olimpiada-matematika-5-8-klass', '/olimpiady/pedagogi/matematika/', 'diapason'),
  ('olimpiada-russkiy-yazyk-1-4-klass', '/olimpiady/pedagogi/russkiy-yazyk/', 'diapason'),
  ('olimpiada-istoriya-5-8-klass', '/olimpiady/pedagogi/istoriya/', 'diapason'),
  ('olimpiada-osnovy-spetsialnoy-psikhologii', '/olimpiady/pedagogi/spetsialnaya-psihologiya/', 'auto'),
  ('olimpiada-matematika-1-4-klass', '/olimpiady/pedagogi/matematika/', 'diapason'),
  ('olimpiada-metodicheskaya-rabota-v-obrazovanii', '/olimpiady/pedagogi/metodist/', 'auto'),
  ('olimpiada-obshchestvoznanie-9-11-klass', '/olimpiady/pedagogi/obshchestvoznanie/', 'diapason'),
  ('olimpiada-metody-korrektsionnoy-raboty-ovz', '/olimpiady/pedagogi/korrektsionnaya-pedagogika/', 'auto'),
  ('olimpiada-sovremennye-tehnologii-i-robototehnika-v-obrazovanii', '/olimpiady/pedagogi/informatika/', 'manual'),
  ('olimpiada-matematika-9-11-klass', '/olimpiady/pedagogi/matematika/', 'diapason'),
  ('olimpiada-informatsionnye-resursy-shkolnoy-biblioteki', '/olimpiady/pedagogi/bibliotekar/', 'auto'),
  ('olimpiada-estestvennye-nauki-9-11-klass', '/olimpiady/shkolnikam/estestvennye-nauki/', 'manual'),
  ('olimpiada-prepodavanie-matematiki-v-sredney-i-starshey-shkole', '/olimpiady/pedagogi/matematika/', 'auto'),
  ('olimpiada-sovremennye-metodiki-prepodavaniya', '/olimpiady/pedagogi/metodist/', 'manual'),
  ('olimpiada-formirovanie-chitatelskoy-gramotnosti', '/olimpiady/pedagogi/literatura/', 'auto'),
  ('olimpiada-metodika-prepodavaniya-fiziki-v-shkole', '/olimpiady/pedagogi/fizika/', 'auto'),
  ('olimpiada-rabota-klassnogo-rukovoditelya', '/olimpiady/pedagogi/klassnoe-rukovodstvo/', 'auto'),
  ('olimpiada-profilaktika-deviantnogo-povedeniya', '/olimpiady/pedagogi/vospitatelnaya-rabota/', 'auto'),
  ('olimpiada-otsenivanie-i-kontrol-v-obrazovanii', '/olimpiady/pedagogi/metodist/', 'manual'),
  ('olimpiada-psikhologicheskoe-soprovozhdenie-ovz', '/olimpiady/pedagogi/spetsialnaya-psihologiya/', 'auto'),
  ('olimpiada-postanovka-zvukov', '/olimpiady/pedagogi/logopediya/', 'auto'),
  ('olimpiada-chrezvychaynye-situatsii-i-zaschita-naseleniya', '/olimpiady/pedagogi/obzh/', 'auto'),
  ('olimpiada-prepodavanie-russkogo-yazyka-v-sredney-shkole', '/olimpiady/pedagogi/russkiy-yazyk/', 'auto'),
  ('olimpiada-metodika-prepodavaniya-matematiki-v-nachalnoy-shkole', '/olimpiady/pedagogi/matematika/', 'auto'),
  ('olimpiada-aktivnye-metody-obucheniya', '/olimpiady/pedagogi/metodist/', 'manual'),
  ('olimpiada-diagnostika-i-korrektsiya-v-rabote-psihologa', '/olimpiady/pedagogi/pedagog-psiholog/', 'auto'),
  ('olimpiada-rabota-sotsialnogo-pedagoga-s-semyoy', '/olimpiady/pedagogi/socialnaya-pedagogika/', 'auto'),
  ('olimpiada-metodika-prepodavaniya-obschestvoznaniya', '/olimpiady/pedagogi/obshchestvoznanie/', 'auto'),
  ('olimpiada-diagnostika-rechevogo-razvitiya', '/olimpiady/pedagogi/logopediya/', 'auto'),
  ('olimpiada-metodika-prepodavaniya-istorii-v-shkole', '/olimpiady/pedagogi/istoriya/', 'auto'),
  ('olimpiada-korrektsionnaya-rabota-defektologa', '/olimpiady/pedagogi/defektologiya/', 'auto'),
  ('olimpiada-hudozhestvennoe-razvitie-mladshih-shkolnikov', '/olimpiady/pedagogi/izo/', 'auto'),
  ('olimpiada-vneurochnaya-deyatelnost-v-obrazovanii', '/olimpiady/pedagogi/administratsiya-upravlenie/', 'manual'),
  ('olimpiada-prepodavanie-fizicheskoy-kultury-v-shkole', '/olimpiady/pedagogi/fizkultura/', 'auto'),
  ('olimpiada-osnovy-korrektsionnoy-pedagogiki', '/olimpiady/pedagogi/korrektsionnaya-pedagogika/', 'auto'),
  ('olimpiada-metodika-prepodavaniya-predmeta-okruzhayuschiy-mir', '/olimpiady/pedagogi/okruzhayushchiy-mir/', 'auto'),
  ('olimpiada-formirovanie-chitatelskoy-gramotnosti-v-1-4-klassah', '/olimpiady/pedagogi/literatura/', 'auto'),
  ('olimpiada-pedagog-organizator-metodika-i-praktika', '/olimpiady/pedagogi/pedagog-organizator/', 'auto'),
  ('olimpiada-normativno-pravovye-osnovy-inklyuzii', '/olimpiady/pedagogi/inklyuzivnoe-obrazovanie/', 'auto'),
  ('olimpiada-himicheskiy-eksperiment-i-bezopasnost-v-shkole', '/olimpiady/pedagogi/himiya/', 'auto'),
  ('olimpiada-fizicheskiy-eksperiment-i-laboratornyy-praktikum', '/olimpiady/pedagogi/fizika/', 'auto'),
  ('olimpiada-vozrastnaya-psihologiya-v-obrazovanii', '/olimpiady/pedagogi/pedagog-psiholog/', 'auto'),
  ('olimpiada-tsifrovye-tehnologii-i-ikt-kompetentsii-pedagoga', '/olimpiady/pedagogi/tsifrovye-tehnologii-obrazovanie/', 'auto'),
  ('olimpiada-organicheskaya-i-neorganicheskaya-himiya-metodika-obucheniya', '/olimpiady/pedagogi/himiya/', 'auto'),
  ('olimpiada-obschestvo-i-chelovek-sovremennye-podhody-k-prepodavaniyu', '/olimpiady/pedagogi/obshchestvoznanie/', 'auto'),
  ('olimpiada-metodika-prepodavaniya-inostrannyh-yazykov-v-shkole', '/olimpiady/pedagogi/inostrannye-yazyki/', 'auto'),
  ('olimpiada-istoriya-rossii-klyuchevye-periody-i-metodika-izucheniya', '/olimpiady/pedagogi/istoriya/', 'auto'),
  ('olimpiada-vospitatelnaya-deyatelnost-v-gpd', '/olimpiady/pedagogi/vospitatel-gpd/', 'auto'),
  ('olimpiada-sovremennye-podhody-k-obucheniyu-fizike', '/olimpiady/pedagogi/fizika/', 'auto'),
  ('olimpiada-podvizhnye-i-sportivnye-igry-v-nachalnoy-shkole', '/olimpiady/pedagogi/fizkultura/', 'auto'),
  ('olimpiada-osnovy-inklyuzivnogo-obrazovaniya', '/olimpiady/pedagogi/inklyuzivnoe-obrazovanie/', 'auto'),
  ('olimpiada-osnovy-defektologii-v-obrazovanii', '/olimpiady/pedagogi/defektologiya/', 'auto'),
  ('olimpiada-organizatsiya-vospitatelnyh-meropriyatiy', '/olimpiady/pedagogi/vospitatelnaya-rabota/', 'auto'),
  ('olimpiada-metodika-raboty-vospitatelya-gpd', '/olimpiady/pedagogi/vospitatel-gpd/', 'auto'),
  ('olimpiada-metodika-prepodavaniya-himii-v-shkole', '/olimpiady/pedagogi/himiya/', 'auto'),
  ('olimpiada-geografiya-rossii-i-mira-sovremennye-podhody', '/olimpiady/pedagogi/geografiya/', 'auto'),
  ('olimpiada-vseobschaya-istoriya-metodika-prepodavaniya', '/olimpiady/pedagogi/istoriya/', 'auto'),
  ('olimpiada-upravlenie-obrazovatelnoy-organizatsiey', '/olimpiady/pedagogi/administratsiya-upravlenie/', 'auto'),
  ('olimpiada-tsifrovye-tekhnologii-na-uroke', '/olimpiady/pedagogi/tsifrovye-tehnologii-obrazovanie/', 'auto'),
  ('olimpiada-psihologo-pedagogicheskoe-soprovozhdenie', '/olimpiady/pedagogi/pedagog-psiholog/', 'auto'),
  ('olimpiada-organizatsiya-inklyuzivnogo-obucheniya', '/olimpiady/pedagogi/inklyuzivnoe-obrazovanie/', 'auto'),
  ('olimpiada-muzykalnoe-razvitie-mladshih-shkolnikov', '/olimpiady/pedagogi/muzyka/', 'auto'),
  ('olimpiada-zdorovesberezhenie-i-zozh-na-urokah-fizkultury', '/olimpiady/pedagogi/fizkultura/', 'auto'),
  ('olimpiada-vospitatelnaya-rabota-v-shkole', '/olimpiady/pedagogi/vospitatelnaya-rabota/', 'auto'),
  ('olimpiada-psikhodiagnostika-detey-ovz', '/olimpiady/pedagogi/spetsialnaya-psihologiya/', 'auto'),
  ('olimpiada-programmirovanie-i-algoritmizatsiya-v-shkolnom-kurse', '/olimpiady/pedagogi/programmirovanie/', 'auto'),
  ('olimpiada-osnovy-tyutorskogo-soprovozhdeniya', '/olimpiady/pedagogi/tyutorstvo/', 'auto'),
  ('olimpiada-obuchenie-grammatike-i-leksike-inostrannogo-yazyka', '/olimpiady/pedagogi/inostrannye-yazyki/', 'auto'),
  ('olimpiada-monitoring-kachestva-obrazovaniya', '/olimpiady/pedagogi/metodist/', 'manual'),
  ('olimpiada-metodika-prepodavaniya-biologii-v-shkole', '/olimpiady/pedagogi/biologiya/', 'auto'),
  ('olimpiada-genetika-i-tsitologiya-v-shkolnom-obrazovanii', '/olimpiady/pedagogi/biologiya/', 'auto'),
  ('olimpiada-estestvennonauchnoe-obrazovanie-v-nachalnoy-shkole', '/olimpiady/pedagogi/okruzhayushchiy-mir/', 'auto'),
  ('olimpiada-sovremennye-tehnologii-na-urokah-russkogo-yazyka-i-literatury', '/olimpiady/pedagogi/russkiy-yazyk/', 'auto'),
  ('olimpiada-rabota-deti-narusheniya-razvitiya', '/olimpiady/pedagogi/defektologiya/', 'auto'),
  ('olimpiada-pravo-i-politika-v-shkolnom-kurse-obschestvoznaniya', '/olimpiady/pedagogi/obshchestvoznanie/', 'auto'),
  ('olimpiada-metodika-prepodavaniya-tehnologii-v-shkole', '/olimpiady/pedagogi/tehnologiya/', 'auto'),
  ('olimpiada-metodika-prepodavaniya-izo-v-nachalnoy-shkole', '/olimpiady/pedagogi/izo/', 'auto'),
  ('olimpiada-metodika-prepodavaniya-fizicheskoy-kultury-v-nachalnoy-shkole', '/olimpiady/pedagogi/fizkultura/', 'auto'),
  ('olimpiada-konstruirovanie-i-modelirovanie-na-urokah-tehnologii', '/olimpiady/pedagogi/tehnologiya/', 'auto'),
  ('olimpiada-esteticheskoe-vospitanie-sredstvami-iskusstva', '/olimpiady/pedagogi/vospitatelnaya-rabota/', 'auto'),
  ('olimpiada-ekologiya-i-evolyutsiya-v-shkolnom-kurse-biologii', '/olimpiady/pedagogi/biologiya/', 'auto'),
  ('olimpiada-distantsionnoe-smeshannoe-obuchenie', '/olimpiady/pedagogi/tsifrovye-tehnologii-obrazovanie/', 'auto'),
  ('olimpiada-diagnostika-pismennoj-rechi', '/olimpiady/pedagogi/logopediya/', 'auto'),
  ('olimpiada-sportivnye-igry-i-sorevnovaniya-v-shkole', '/olimpiady/pedagogi/fizkultura/', 'auto'),
  ('olimpiada-sovremennye-tehnologii-obucheniya-angliyskomu-v-nachalnoy-shkole', '/olimpiady/pedagogi/inostrannye-yazyki/', 'auto'),
  ('olimpiada-rabota-s-roditelyami-v-klassnom-rukovodstve', '/olimpiady/pedagogi/klassnoe-rukovodstvo/', 'auto'),
  ('olimpiada-profilaktika-bezopasnost-v-shkole', '/olimpiady/pedagogi/obzh/', 'auto'),
  ('olimpiada-proektirovanie-obrazovatelnyh-programm', '/olimpiady/pedagogi/metodist/', 'auto'),
  ('olimpiada-prepodavanie-informatiki-v-shkole-po-fgos', '/olimpiady/pedagogi/informatika/', 'auto'),
  ('olimpiada-organizatsiya-raboty-v-gruppe-prodlyonnogo-dnya', '/olimpiady/pedagogi/vospitatel-gpd/', 'auto'),
  ('olimpiada-obsledovanie-zvukoproiznosheniya', '/olimpiady/pedagogi/logopediya/', 'auto'),
  ('olimpiada-obschestvovedcheskiy-blok-kursa-okruzhayuschiy-mir', '/olimpiady/pedagogi/okruzhayushchiy-mir/', 'auto'),
  ('olimpiada-narodnoe-i-dekorativno-prikladnoe-iskusstvo-na-urokah-izo', '/olimpiady/pedagogi/izo/', 'auto'),
  ('olimpiada-mirovaya-hudozhestvennaya-kultura-metodika-prepodavaniya', '/olimpiady/pedagogi/mhk/', 'auto'),
  ('olimpiada-metodika-prepodavaniya-muzyki-v-nachalnoy-shkole', '/olimpiady/pedagogi/muzyka/', 'auto'),
  ('olimpiada-individualizatsiya-obrazovaniya-i-tyutorstvo', '/olimpiady/pedagogi/tyutorstvo/', 'auto'),
  ('olimpiada-formirovanie-inoyazychnoy-kompetentsii-mladshih-shkolnikov', '/olimpiady/pedagogi/inostrannye-yazyki/', 'auto'),
  ('olimpiada-avtomatizatsiya-zvukov', '/olimpiady/pedagogi/logopediya/', 'auto'),
  ('olimpiada-tyutorskie-tehnologii-v-praktike', '/olimpiady/pedagogi/tyutorstvo/', 'auto'),
  ('olimpiada-tvorcheskie-proekty-i-prakticheskaya-deyatelnost-na-urokah-tehnologii', '/olimpiady/pedagogi/tehnologiya/', 'auto'),
  ('olimpiada-pervaya-pomosch-i-meditsinskaya-podgotovka-v-obzh', '/olimpiady/pedagogi/obzh/', 'auto'),
  ('olimpiada-osnovy-sotsialnoy-pedagogiki', '/olimpiady/pedagogi/socialnaya-pedagogika/', 'auto'),
  ('olimpiada-osnovy-klassnogo-rukovodstva', '/olimpiady/pedagogi/klassnoe-rukovodstvo/', 'auto'),
  ('olimpiada-obshchee-nedorazvitie-rechi', '/olimpiady/pedagogi/logopediya/', 'auto'),
  ('olimpiada-muzykalnoe-nasledie-i-sovremennaya-muzyka-na-urokah-v-nachalnoy-shkole', '/olimpiady/pedagogi/muzyka/', 'auto'),
  ('olimpiada-metodika-prepodavaniya-tehnologii-v-nachalnoy-shkole', '/olimpiady/pedagogi/tehnologiya/', 'auto'),
  ('olimpiada-metodika-obucheniya-angliyskomu-yazyku-v-nachalnoy-shkole', '/olimpiady/pedagogi/inostrannye-yazyki/', 'auto'),
  ('olimpiada-formirovanie-matematicheskogo-myshleniya-mladshih-shkolnikov', '/olimpiady/pedagogi/matematika/', 'auto'),
  ('olimpiada-formirovanie-leksiko-grammaticheskogo-stroya', '/olimpiady/pedagogi/logopediya/', 'auto'),
  ('olimpiada-differentsiatsiya-zvukov', '/olimpiady/pedagogi/logopediya/', 'auto'),
  ('olimpiada-strategicheskoe-razvitie-obrazovatelnogo-uchrezhdeniya', '/olimpiady/pedagogi/administratsiya-upravlenie/', 'auto'),
  ('olimpiada-spetsialnaya-pedagogika-i-nozologii', '/olimpiady/pedagogi/defektologiya/', 'auto'),
  ('olimpiada-razvitie-rechi-na-urokah-russkogo-yazyka-v-nachalnoy-shkole', '/olimpiady/pedagogi/russkiy-yazyk/', 'auto'),
  ('olimpiada-mezhkulturnaya-kompetentsiya-i-sovremennye-tehnologii-v-obuchenii-yazykam', '/olimpiady/pedagogi/inostrannye-yazyki/', 'auto'),
  ('olimpiada-metodika-prepodavaniya-muzyki-v-shkole', '/olimpiady/pedagogi/muzyka/', 'auto'),
  ('olimpiada-metodika-prepodavaniya-geografii-v-shkole', '/olimpiady/pedagogi/geografiya/', 'auto'),
  ('olimpiada-metodika-obucheniya-russkomu-yazyku-v-nachalnoy-shkole', '/olimpiady/pedagogi/russkiy-yazyk/', 'auto'),
  ('olimpiada-metodika-literaturnogo-obrazovaniya-v-shkole', '/olimpiady/pedagogi/literatura/', 'auto'),
  ('olimpiada-kartografiya-i-geoinformatika-v-shkolnom-obrazovanii', '/olimpiady/pedagogi/geografiya/', 'auto'),
  ('olimpiada-informatsionnaya-bezopasnost-obrazovanie', '/olimpiady/pedagogi/tsifrovye-tehnologii-obrazovanie/', 'auto'),
  ('olimpiada-formirovanie-gramotnosti-mladshih-shkolnikov', '/olimpiady/pedagogi/russkiy-yazyk/', 'auto'),
  ('olimpiada-dizayn-i-dekorativno-prikladnoe-tvorchestvo-na-urokah-tehnologii', '/olimpiady/pedagogi/izo/', 'auto'),
  ('olimpiada-detskaya-literatura-i-krug-chteniya-mladshih-shkolnikov', '/olimpiady/pedagogi/literatura/', 'auto'),
  ('olimpiada-algebra-i-nachala-analiza-metodika-prepodavaniya', '/olimpiady/pedagogi/matematika/', 'auto');
