-- Обсуждения блога. Старые отзывы продуктов не изменяются.
CREATE TABLE IF NOT EXISTS blog_comments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    publication_id INT UNSIGNED NOT NULL,
    parent_id INT UNSIGNED NULL,
    root_id INT UNSIGNED NULL,
    user_id INT UNSIGNED NULL,
    author_name VARCHAR(120) NOT NULL,
    author_role VARCHAR(160) NULL,
    body TEXT NOT NULL,
    rating TINYINT UNSIGNED NULL,
    vote_token CHAR(32) NOT NULL,
    rating_token CHAR(32) GENERATED ALWAYS AS (CASE WHEN rating IS NOT NULL THEN vote_token ELSE NULL END) STORED,
    request_key CHAR(32) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    ip_address VARCHAR(45) NULL,
    status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
    moderation_reason VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    moderated_at TIMESTAMP NULL,
    UNIQUE KEY uq_blog_rating (publication_id, rating_token),
    UNIQUE KEY uq_blog_request (publication_id, vote_token, request_key),
    KEY idx_blog_roots (publication_id, parent_id, status, id),
    KEY idx_blog_parent (parent_id, status, id),
    KEY idx_blog_root (root_id, status, id),
    KEY idx_blog_moderation (status, id),
    CONSTRAINT chk_blog_rating CHECK (rating IS NULL OR (rating BETWEEN 1 AND 5 AND parent_id IS NULL)),
    CONSTRAINT fk_blog_parent FOREIGN KEY (parent_id) REFERENCES blog_comments(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
